name: Deploy Frontend to AWS S3 (PROD)

on:
  push:
    branches:
      - v3-aws-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build frontend
        run: |
          VITE_API_BASE_URL="${{ secrets.VITE_API_BASE_URL_PROD }}" \
          VITE_REST_API_KEY="${{ secrets.VITE_REST_API_KEY }}" \
          VITE_KAKAO_MAP_KEY="${{ secrets.VITE_KAKAO_MAP_KEY }}" \
          pnpm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 # 서울 리전 

      - name: Upload to AWS S3
        run: |
          aws s3 sync ./dist s3://v3-prod-frontend-bucket --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
