name: Deploy Frontend to GCP Cloud Storage

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: elevated-valve-459107-h8
          version: latest

      # Step 3: pnpm 설치
      - name: Install pnpm
        run: |
          npm install -g pnpm

      # Step 4: 종속성 설치
      - name: Install dependencies
        run: |
          pnpm install

      # Step 5: 프론트엔드 빌드 (Vite 사용)
      - name: Build frontend
        run: |
          VITE_API_BASE_URL="http://jeff-cloud.com/" \
          VITE_REST_API_KEY="9333a34b6c9de8d1db66955c4b396b21" \
          pnpm run build

      # Step 6: GCP Cloud Storage에 빌드된 파일 업로드
      - name: Upload to GCP Cloud Storage
        run: |
          gsutil -m rsync -r ./dist gs://frontend-cafeboo

      # Step 7: Cloud CDN 캐시 무효화 -> 최신 파일을 즉시 반영
      - name: Invalidate CDN cache
        run: |
          gcloud compute url-maps invalidate-cdn-cache doraa-url-map \
            --path "/*" \
            --global
