name: Deploy Frontend to GCP Cloud Storage

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: elevated-valve-459107-h8
          version: latest

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build frontend
        run: |
          pnpm run build

      - name: Upload to GCP Cloud Storage
        run: |
          gsutil -m rsync -r ./dist gs://frontend-cafeboo

      - name: Invalidate CDN cache
        run: |
          gcloud compute url-maps invalidate-cdn-cache doraa-url-map \
            --path "/*" \
            --global
